### ISSUE TITLE
TMB with GPU

### ISSUE THREAD

**Issue by kaskr** [TMB-ADMB-Workshops/June2016-Developers-Workshop#6]
Does anyone have an nvidia GPU ? (I don't).
Here's an idea for a small workshop project with potential to speedup 4D fishery models:
Install nvidia BLAS (nvblas).
- Run R with `LD_PRELOAD=/path/to/libnvblas.so R`
- Source `tmb_examples/ar1_4D.R` with increased n and measure speedup.

**Comment by gavinfay** [comment]
I think I have finally got this working (on Ubuntu 14.04).
Tried n=8 and n=10. Here are the results from system.time(source("ar1_4D.R")).
For n=8, improvement was minimal.
For n=10, run time with GPU was 40% that when run without GPU.

#n=8
#with nvblas
user  system elapsed 
50.327   3.250  53.608 
#n=8
#normal R
user  system elapsed 
60.794   0.105  60.928 

#n=10
#with nvblas
user  system elapsed 
240.180  24.160 264.414
#n=10
#normal R
user  system elapsed 
578.301   0.681 579.208

**Comment by kaskr** [comment]
Thanks for trying this! Do you get better speedup on something like

```
x <- diag(1e3)+1
system.time(x %*% x)
```
